apiVersion: v1
kind: ReplicationController
metadata:
  name: fibserver-rc
spec:
  replicas: 3
  selector:
    app: fibserver
  template:
    metadata:
      labels:
        app: fibserver
    spec:
      containers:
        - name: fib-server
          image: cgianelle1976/fibonacci:arm32-1.0
          ports:
          - containerPort: 3184