apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fibserver-deployment
  labels:
    version: 1.1.0
spec:
  replicas: 6
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: fibserver
    spec:
      containers:
        - name: fibserver-pod
          image: cgianelle1976/fibonacci:arm32-1.1.0
          ports:
          - containerPort: 3184
          env:
            - name: SECRET_FIRST_NAME
              valueFrom:
                secretKeyRef:
                  name:  my-super-secret-secret
                  key:  my-first-name
            - name: SECRET_LAST_NAME
              valueFrom:
                secretKeyRef:
                  name: my-super-secret-secret
                  key: my-last-name