apiVersion: v1
kind: Pod
metadata:
  name: fibonacci-pod
  labels:
    version: v1
spec:
  containers:
    - name: fib-server
      image: cgianelle1976/fibonacci:arm32-1.0
      ports:
        - containerPort: 3184
